global:
  scrape_interval: 30s # By default, scrape targets every 5 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'KybCheck-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'IdentityServer'
    metrics_path: /metrics
    static_configs:
      - targets: ['KybCheck.IdentityProvider.IdentityServer:80']
  - job_name: 'DataCollectionApi'
    metrics_path: /metrics
    static_configs:
      - targets: ['KybCheck.DataCollection.Api:80']
  -job_name: 'FileApi'
    metrics_path: /metrics
    static_configs:
      - targets: ['KybCheck.FileApi:80']